spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddsp_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: 3333
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true #打印sql
    properties:
      hibernate:
        format_sql: true  #格式化sql
server:
  port: 9999

